/**
 * Each JSON is produced by tools/trace-tab/ — traced from a real photograph
 * (main.py) or generated by its synthesis tools (invent.py/synthesize.py,
 * see source.notes); one file per trace keeps diffs readable when traces are
 * added or replaced.
 */

import type { Point } from '../../../model/types.js';
import { diagnostics } from '../../../diagnostics.js';
import tab02 from './02-tab-a.json';
import tab03 from './03-tab-b.json';
import tab04 from './04-tab-c.json';
import tab05 from './05-tab-d.json';
import tab06 from './06-tab-e.json';
import tab07 from './07-tab-f.json';
import tab08 from './08-tab-g.json';
import tab09 from './09-tab-h.json';
import tab10 from './10-tab-i.json';
import tab11 from './11-tab-j.json';
import tab12 from './12-tab-k.json';
import tab13 from './13-tab-l.json';
import tab14 from './14-tab-m.json';
import tab15 from './15-tab-n.json';
import tab16 from './16-tab-o.json';
import tab17 from './17-tab-p.json';
import tab18 from './18-tab-q.json';
import tab19 from './19-tab-r.json';
import tab20 from './20-tab-s.json';
import tab21 from './21-tab-t.json';
import tab22 from './22-tab-u.json';
import tab23 from './23-tab-v.json';
import tab24 from './24-tab-w.json';
import tab25 from './25-tab-x.json';
import tab26 from './26-tab-y.json';
import tab27 from './27-tab-z.json';
import tab28 from './28-tab-aa.json';
import tab29 from './29-tab-ab.json';
import tab30 from './30-tab-ac.json';
import tab31 from './31-tab-ad.json';
import tab32 from './32-tab-ae.json';
import tab33 from './33-tab-af.json';
import tab34 from './34-tab-ag.json';
import tab35 from './35-tab-ah.json';
import tab36 from './36-tab-ai.json';
import tab37 from './37-tab-aj.json';
import tab38 from './38-tab-ak.json';
import tab39 from './39-tab-al.json';
import tab40 from './40-tab-am.json';
import tab41 from './41-tab-an.json';

export interface TracedLandmarks {
    /** Y of the tab's highest point, normalized to chord length. */
    apex_y: number;
    /** Widest point of the head. */
    head: { y: number; width: number; center_x: number };
    /** Narrowest point of the neck. */
    neck: { y: number; width: number; center_x: number };
}

export interface TracedTemplate {
    /** Stable identifier, used as filename stem. */
    id: string;
    source: {
        photo: string;
        captured: string;
        notes?: string;
    };
    /**
     * BezierPath in normalized neck-frame: starts at (0,0), ends at (1,0),
     * protrudes in +Y. Flat array, length 3n+1 for n cubic segments.
     */
    path: readonly Point[];
    landmarks: TracedLandmarks;
}

/**
 * Validates each checked-in trace at import — structural problems (missing
 * fields, NaN landmarks, wrong-length `path`) throw at startup instead of
 * propagating NaNs through the pinch/scale math. Also backs the schema tests
 * in `index.test.ts`, so production and tests share one narrowing.
 */
export function assertTracedTemplate(raw: unknown, label: string): TracedTemplate {
    const fail = (msg: string): never => {
        throw new Error(`Trace ${label}: ${msg}`);
    };
    if (!raw || typeof raw !== 'object') fail('not an object');
    const t = raw as Record<string, unknown>;
    if (typeof t.id !== 'string') fail('missing string id');

    if (!t.source || typeof t.source !== 'object') fail('missing source object');
    const src = t.source as Record<string, unknown>;
    if (typeof src.photo !== 'string') fail('source.photo not a string');
    if (typeof src.captured !== 'string') fail('source.captured not a string');

    if (!Array.isArray(t.path)) fail('path is not an array');
    const path = t.path as unknown[];
    if (path.length < 4 || (path.length - 1) % 3 !== 0) {
        fail(`path length must be 3n+1 (n ≥ 1); got ${path.length}`);
    }
    for (let i = 0; i < path.length; i++) {
        const p = path[i] as Record<string, unknown> | null;
        if (!p || typeof p !== 'object'
            || typeof p.x !== 'number' || !Number.isFinite(p.x)
            || typeof p.y !== 'number' || !Number.isFinite(p.y)) {
            fail(`path[${i}] is not a finite Point`);
        }
    }

    if (!t.landmarks || typeof t.landmarks !== 'object') fail('missing landmarks');
    const lm = t.landmarks as Record<string, unknown>;
    const finiteAt = (key: string, v: unknown): void => {
        if (typeof v !== 'number' || !Number.isFinite(v)) {
            fail(`landmarks.${key} is not a finite number`);
        }
    };
    finiteAt('apex_y', lm.apex_y);
    for (const part of ['head', 'neck'] as const) {
        const node = lm[part] as Record<string, unknown> | undefined;
        if (!node || typeof node !== 'object') fail(`landmarks.${part} missing`);
        finiteAt(`${part}.y`, node!.y);
        finiteAt(`${part}.width`, node!.width);
        finiteAt(`${part}.center_x`, node!.center_x);
    }

    return raw as TracedTemplate;
}

export const TRACED_TEMPLATES: readonly TracedTemplate[] = [
    assertTracedTemplate(tab02, '02-tab-a'),
    assertTracedTemplate(tab03, '03-tab-b'),
    assertTracedTemplate(tab04, '04-tab-c'),
    assertTracedTemplate(tab05, '05-tab-d'),
    assertTracedTemplate(tab06, '06-tab-e'),
    assertTracedTemplate(tab07, '07-tab-f'),
    assertTracedTemplate(tab08, '08-tab-g'),
    assertTracedTemplate(tab09, '09-tab-h'),
    assertTracedTemplate(tab10, '10-tab-i'),
    assertTracedTemplate(tab11, '11-tab-j'),
    assertTracedTemplate(tab12, '12-tab-k'),
    assertTracedTemplate(tab13, '13-tab-l'),
    assertTracedTemplate(tab14, '14-tab-m'),
    assertTracedTemplate(tab15, '15-tab-n'),
    assertTracedTemplate(tab16, '16-tab-o'),
    assertTracedTemplate(tab17, '17-tab-p'),
    assertTracedTemplate(tab18, '18-tab-q'),
    assertTracedTemplate(tab19, '19-tab-r'),
    assertTracedTemplate(tab20, '20-tab-s'),
    assertTracedTemplate(tab21, '21-tab-t'),
] as const;

/**
 * Version 1 trace set: the original ordered library. FROZEN — never reorder or
 * remove. A new set ships as a new TRACE_SETS entry plus a
 * CURRENT_TRACE_SET_VERSION bump, leaving older snapshots byte-for-byte intact
 * so old share-links still reproduce.
 */
const TRACE_SET_V1: readonly TracedTemplate[] = TRACED_TEMPLATES;

/**
 * Version 2 additions: invented in the classic-tab family by
 * tools/trace-tab/invent.py (seed 20260823), not photographed. FROZEN like
 * v1 once shipped.
 */
const TRACE_SET_V2_ADDITIONS: readonly TracedTemplate[] = [
    assertTracedTemplate(tab22, '22-tab-u'),
    assertTracedTemplate(tab23, '23-tab-v'),
    assertTracedTemplate(tab24, '24-tab-w'),
    assertTracedTemplate(tab25, '25-tab-x'),
    assertTracedTemplate(tab26, '26-tab-y'),
    assertTracedTemplate(tab27, '27-tab-z'),
    assertTracedTemplate(tab28, '28-tab-aa'),
    assertTracedTemplate(tab29, '29-tab-ab'),
    assertTracedTemplate(tab30, '30-tab-ac'),
    assertTracedTemplate(tab31, '31-tab-ad'),
    assertTracedTemplate(tab32, '32-tab-ae'),
    assertTracedTemplate(tab33, '33-tab-af'),
    assertTracedTemplate(tab34, '34-tab-ag'),
    assertTracedTemplate(tab35, '35-tab-ah'),
    assertTracedTemplate(tab36, '36-tab-ai'),
    assertTracedTemplate(tab37, '37-tab-aj'),
    assertTracedTemplate(tab38, '38-tab-ak'),
    assertTracedTemplate(tab39, '39-tab-al'),
    assertTracedTemplate(tab40, '40-tab-am'),
    assertTracedTemplate(tab41, '41-tab-an'),
];

const TRACE_SET_V2: readonly TracedTemplate[] = [...TRACE_SET_V1, ...TRACE_SET_V2_ADDITIONS];

const TRACE_SETS: Readonly<Record<number, readonly TracedTemplate[]>> = {
    1: TRACE_SET_V1,
    2: TRACE_SET_V2,
};

/**
 * Unknown versions fall back to v1 — defensive only; the share-link decoder
 * clamps `wf.tv` to [1, CURRENT_TRACE_SET_VERSION], so a known client never
 * asks for a version it lacks.
 */
export function getTracedTemplates(version: number): readonly TracedTemplate[] {
    const set = TRACE_SETS[version];
    if (set) return set;
    // Unreachable on a correct client; breadcrumb so a regressed upstream clamp
    // doesn't fail silently.
    diagnostics.warn(`getTracedTemplates: unknown trace-set version ${version}, falling back to v1`);
    return TRACE_SET_V1;
}
